name: One-Click Intraday Momentum (1m, scalp)

on:
  workflow_dispatch:
    inputs:
      tickers:
        description: "Tickers (comma-separated)"
        required: false
        default: "OPEN,PLTR"
      period:
        description: "History period (e.g. 7d, 14d, 30d)"
        required: false
        default: "7d"
      interval:
        description: "Bar interval (e.g. 1m, 5m)"
        required: false
        default: "1m"
      horizon:
        description: "Forward horizon in minutes (labeling)"
        required: false
        default: "15"
      thr:
        description: "Move threshold (e.g. 0.005 = 0.5%)"
        required: false
        default: "0.005"
      prob_th:
        description: "Min class probability to issue BUY/SELL"
        required: false
        default: "0.55"

jobs:
  train:
    name: Train intraday momentum
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance numpy pandas scikit-learn matplotlib

      - name: Run trainer
        env:
          TICKERS: ${{ inputs.tickers }}
          PERIOD: ${{ inputs.period }}
          INTERVAL: ${{ inputs.interval }}
          HORIZON: ${{ inputs.horizon }}
          THR: ${{ inputs.thr }}
          PROB_TH: ${{ inputs.prob_th }}
        run: |
          python train_intraday.py \
            --tickers "${TICKERS:-OPEN,PLTR}" \
            --period "${PERIOD:-7d}" \
            --interval "${INTERVAL:-1m}" \
            --horizon "${HORIZON:-15}" \
            --thr "${THR:-0.005}" \
            --prob_th "${PROB_TH:-0.55}"

      - name: Upload artifacts (charts & CSV)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: intraday-out
          path: |
            out/**/*
          if-no-files-found: ignore
